version: '3'
services:
  node-app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=pranav
      - MONGO_PASSWORD=pass
    command: npm run dev
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=pranav
      - MONGO_INITDB_ROOT_PASSWORD=pass